source "https://rubygems.org"

gem "foreman"
gem "arduino_ir_remote"
gem "logger"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-rocketio"
gem "thin"
gem "serialport"
gem "hashie"
gem "event_emitter"
gem "haml"
gem "sass"
